### ISSUE TITLE
HTML Warning: <form> anchor "pp_count_form" already defined when "Include item-count drop-down" is true

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#14]
The form name is the same for the top and bottom links.

**Comment by lat9** [comment]
Yes, this plugins needs a bit of "care & feeding"; thanks for the report.

**Comment by torvista** [comment]
I did some already in my branch, as a base spring clean, prior to fixing an
issue I have with this.

**Comment by torvista** [comment]
similarly for pp_page_form

**Comment by lat9** [comment]
I'm not seeing the additional form using the current repository file-set; @torvista could you recheck?

Note, too, that the changes for #20 and #15 could be problematic (for the styling).  Please recheck.

**Comment by torvista** [comment]
If you are looking at my fork....I have no idea what was what and when....I'll see when today's issues are resolved.

**Comment by torvista** [comment]
I doubt I resolved this....I guess some variable has to keep count of the calls to this module to put a unique suffix on the form name..or just add a timestamp to it!!

**Comment by torvista** [comment]
Sorry, I forgot about this duplicate form stuff...
![Clipboard02](https://user-images.githubusercontent.com/4391026/84597766-715c6800-ae66-11ea-9819-30d08474c85e.gif)

**Comment by lat9** [comment]
What page is this on?

**Comment by torvista** [comment]
Any that have the Items per page dropdown showing.

**Comment by lat9** [comment]
Ah, the distinction is that the information _is_ shown and there's neither a top nor bottom submit button rendered.

**Comment by lat9** [comment]
There you go; suffixed the form-name based on the number of times that formatting block was called.

**Comment by torvista** [comment]
ok, note that pp_page_form needs the same.

**Comment by lat9** [comment]
All better.
