### ISSUE TITLE
call to undefined method products_pagination_observer::currentPosition()

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#22]
156 site.

> PHP Fatal error:  Uncaught Error: Call to undefined method products_pagination_observer::currentPosition() in ...\tienda\includes\templates\template_default\templates\tpl_pp_products_next_previous.php:10
> Stack trace:
> #0 ...\tienda\includes\templates\motorvista5\templates\tpl_products_next_previous.php(22): require()
> #1 ...\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php(41): require('D:\\OneDrive\\Bus...')
> #2 ...\tienda\includes\modules\pages\product_info\main_template_vars.php(223): require('D:\\OneDrive\\Bus...')
> #3 ...\tienda\includes\templates\motorvista5\common\tpl_main_page.php(175): require('D:\\OneDrive\\Bus...')
> #4 ...\tienda\index.php(97): require('D:\\OneDrive\\Bus...')
> #5 {main}
>   thrown in ...\tienda\includes\templates\template_default\templates\tpl_pp_products_next_previous.php on line 10
> 
> Request URI: /tienda/manufacturers/rg-racing/oil-cooler-guards/rg-ocg0020-oil-cooler-guard-ducati-multistrada-1200-2010-2014, IP address: 127.0.0.1
> --> PHP Fatal error: Uncaught Error: Call to undefined method products_pagination_observer::currentPosition() in ...\tienda\includes\templates\template_default\templates\tpl_pp_products_next_previous.php:10
> Stack trace:
> #0 ...\tienda\includes\templates\motorvista5\templates\tpl_products_next_previous.php(22): require()
> #1 ...\tienda\includes\templates\motorvista5\templates\tpl_product_info_display.php(41): require('D:\\OneDrive\\Bus...')
> #2 ...\tienda\includes\modules\pages\product_info\main_template_vars.php(223): require('D:\\OneDrive\\Bus...')
> #3 ...\tienda\includes\templates\motorvista5\common\tpl_main_page.php(175): require('D:\\OneDrive\\Bus...')
> #4 ...\tienda\index.php(97): require('D:\\OneDrive\\Bus...')
> #5 {main}
>   thrown in ...\tienda\includes\templates\template_default\templates\tpl_pp_products_next_previous.php on line 10.

**Comment by lat9** [comment]
That little change should do it.  That's what I get for cropping no-longer-used elements and not re-testing.
