### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'splitPageResults' not found

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#24]
ZC157 vanilla

> PHP Fatal error:  Uncaught Error: Class 'splitPageResults' not found in ...zencart-157\includes\modules\responsive_classic\product_listing.php:14
Stack trace:
#0 ...zencart-157\includes\templates\responsive_classic\templates\tpl_modules_product_listing.php(11): include()
#1 ...zencart-157\includes\templates\responsive_classic\templates\tpl_index_product_list.php(112): require('D:\\OneDrive\\Dev...')
#2 ...zencart-157\includes\modules\pages\index\main_template_vars.php(232): require('D:\\OneDrive\\Dev...')
#3 ...zencart-157\includes\templates\responsive_classic\common\tpl_main_page.php(177): require('D:\\OneDrive\\Dev...')
#4 ...zencart-157\index.php(97): require('D:\\OneDrive\\Dev...')
#5 {main}
  thrown in ...zencart-157\includes\modules\responsive_classic\product_listing.php on line 14

[07-Jun-2020 23:11:38 Europe/Madrid] Request URI: /zencart-157/index.php?main_page=index&cPath=1_5_2282, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Error: Class 'splitPageResults' not found in ...zencart-157\includes\modules\responsive_classic\product_listing.php:14
Stack trace:
#0 ...zencart-157\includes\templates\responsive_classic\templates\tpl_modules_product_listing.php(11): include()
#1 ...zencart-157\includes\templates\responsive_classic\templates\tpl_index_product_list.php(112): require('D:\\OneDrive\\Dev...')
#2 ...zencart-157\includes\modules\pages\index\main_template_vars.php(232): require('D:\\OneDrive\\Dev...')
#3 ...zencart-157\includes\templates\responsive_classic\common\tpl_main_page.php(177): require('D:\\OneDrive\\Dev...')
#4 ...zencart-157\index.php(97): require('D:\\OneDrive\\Dev...')
#5 {main}
  thrown in ...zencart-157\includes\modules\responsive_classic\product_listing.php on line 14.

**Comment by lat9** [comment]
Possibly due to [this](https://github.com/zencart/zencart/issues/3574) auto-loading change in zc157?

**Comment by lat9** [comment]
There's an update that enables the interoperation.
