### ISSUE TITLE
numbered links nav has class "pagination", but that style is not defined

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#25]
![Clipboard01](https://user-images.githubusercontent.com/4391026/83981246-7e380380-a91c-11ea-8a0d-adcf36d93519.gif)

...so the links are unstyled

restoring the class to "prod-pagination pagination-links" corrects this.

**Comment by lat9** [comment]
Hmm, they're styled on my local test site.  Did you copy/merge the updated .css file to your template's /css sub-directory?

**Comment by lat9** [comment]
Never mind; I'd been totally focused on getting the links to look right on the products' listing page.
