### ISSUE TITLE
handling of quotes in category name

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#27]
If there is quoted text in the category name, the title attribute for View Product Listing is corrupted as the quotes are not handled.
I did this in the observer:
original
`return sprintf(PP_TEXT_PRODUCT_LISTING_TITLE, $this->category_name);`
to
`        return htmlentities(sprintf(PP_TEXT_PRODUCT_LISTING_TITLE, $this->category_name), ENT_QUOTES, "UTF-8", false);`

**Comment by torvista** [comment]
included in this https://github.com/lat9/product_pagination/pull/30

**Comment by lat9** [comment]
Changes incorporated in #31.
