### ISSUE TITLE
ZC2.0.0 Alpha1: Fatal error Cannot declare class splitPageResults, because the name is already in use

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#28]
With the Laravel update from yesterday, I get this fatal error (Symphony exception), which is cleared (but not fixed) by temporarily disabling config.pagination.php.

**Comment by lat9** [comment]
I'll wait for that Laravel update to settle and address this (if still present) at that time.

**Comment by torvista** [comment]
Do you think there is a possibility to add this to core? It seems something that I see everywhere else.

**Comment by lat9** [comment]
I dunno; open a discussion on the zencart repo and see if there's a consensus.
