### ISSUE TITLE
use of $debug and $this->debug

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#29]
https://github.com/lat9/product_pagination/blob/74ac9248f0cb8982123dede839ffdbb6d2fbdad6/includes/classes/pp_split_page_results.php#L25-L29

How is this supposed to be used for debugging?
Something similar is in freeoptions.php but I find no documentation.

**Comment by lat9** [comment]
That'll be part of the next release; essentially mimicking the base split_page_results.php class and echoing those strings to the display if the `$debug` input indicates as such.
