### ISSUE TITLE
Suggestion: urls to link to id/anchor to maintain position

### ISSUE THREAD

**Issue by torvista** [lat9/product_pagination#35]
For example in a category with a significant description, the paging links are somewhat down the page.

Clicking on a page number reloads another page, but to the top: it requires scrolling down each time to click on another page.
 A better experience would be to leave the page/cursor over the links again: link to an id.

The fly seems to be that the common links for top and bottom don't know whether to point to the top or bottom wrapper, so I guess 
 it would be only achievable by some JavaScript witchcraft.

**Comment by lat9** [comment]
Better to make this suggestion on the base Zen Cart repo; it's a template thingie.
